### PR TITLE
Serve SPA in AWS S3 and Cloudfront Services - Task 2

### PR DESCRIPTION
**Pull request by MarcoGuzmanR**
Implemented two projects, one for manual deployment and the other for automated deployment with serverless just to not loose reference of the first task.

I was able to deploy manually the shop site in Cloudfront through S3 and added the invalidation properly.

I was able to configure the serverless plugin but not working as expected. When I tried to deploy new changes to the instance, it was always creating new buckets. I tried running the different tasks inside the package but with no luck. I change some configuration with no luck either. At this point, I'm not pretty sure how the plugin works exactly. I'll need to review further in that matter.

I applied the S3 policies but it's public for both, S3 and Cloudfront. Not sure why it's occurring this but I'll need to check this too.

Let me know if you have any questions or comments.

### CODE REVIEW

**Comment by sasarik** [comment]
Hi, @MarcoGuzmanR  -  the `.serverless_plugins/serverless-single-page-app-plugin.js` here should work as is and seems not require to configure somehow especially; I think its done by this course creators to make our life easer :)
Unfortunately I can't grade this as 100 coz You still can't manage automatic deployment of Your changes; I would advise You to remove [this line](https://github.com/MarcoGuzmanR/shop-react-redux-cloudfront/pull/1/files#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519R41)
It should work  - as is (why not, - coz serverless automatically takes into account the plugins presence:
image
)
and check / perform setup -> deploy -> make changes -> deploy again -> make changes -> deploy etc. 
to be prepared for next modules and evaluate this module requirements (i.e. this one "The app can be built and deployed by running npm script command")

**Comment by MarcoGuzmanR** [comment]
Thanks for your feedback @sasarik. I just updated the PR.

I also fixed the permissions for S3 and Cloudfront distribution. Now the serverless link is now accessible only from the Cloudfront link, not from S3.

**Review by sasarik — APPROVED** [review]

**Comment by ytroshka** [comment]
Hi @MarcoGuzmanR, could you please check Cloudfront link for Serverless deployment task?
It's not available now.

**Comment by MarcoGuzmanR** [comment]
Hi @ytroshka. Can you try again https://d12okp4zn60tmk.cloudfront.net please?

**Comment by ytroshka** [comment]
@MarcoGuzmanR,
I see AccessDenied error
image

**Comment by MarcoGuzmanR** [comment]
@ytroshka that's weird.

I just tried with three different browsers and I'm seeing the page 😨

**Comment by MarcoGuzmanR** [comment]
@ytroshka I just tried in another personal device and I'm seeing the AccessDenied error. Not sure why.

**Comment by MarcoGuzmanR** [comment]
@ytroshka I just tried with https and worked fine.

**Comment by ytroshka** [comment]
@MarcoGuzmanR as you can see on the screenshot, I opened https version. Error is still present.

**Pull request merged**
